"use client";
import { 
	DISPLAY_COMPONENTS, 
	INPUT_COMPONENT_FIELDS, 
	configEntriesMap, 
	configEntry, 
	contentMapping, 
	displayComponents,
  displayMapping,
  inputMapping,
} from "@/types/toolchain-interface";

// AUTOGENERATED IMPORTS; DO NOT MODIFY THIS COMMENT

// END AUTOGENERATED IMPORTS; DO NOT MODIFY THIS COMMENT


import { useToolchainContextAction } from "@/app/app/context-provider";

export function ToolchainComponentMapper({
	info
}:{
	info: contentMapping
}) {
  
	// const {
  //   toolchainState,
  // } = useToolchainContextAction();

  const getEffectiveConfig = (info : inputMapping) => {
    let effectiveConfig : configEntriesMap = new Map();
    const default_fields = INPUT_COMPONENT_FIELDS[info.display_as];
    if (default_fields.config) {
      for (const entry of default_fields.config) {
        effectiveConfig.set(entry.name, {name: entry.name, value: entry.default});
      }
    }
    for (const entry of info.config) {
      effectiveConfig.set(entry.name, entry);
    }

    return effectiveConfig;
  }
  
	switch(info.display_as) {
		
    // AUTOGENERATED SWITCH; DO NOT MODIFY THIS COMMENT
    default:
      return (
        <></>
      );
    // END AUTOGENERATED SWITCH; DO NOT MODIFY THIS COMMENT
    
	}
}

export default function DisplayMappings({
	info
}:{
	info: contentMapping
}) {

	return (
		<>
		{(DISPLAY_COMPONENTS.includes(info.display_as as displayComponents)) ? ( // Display Component
      <ToolchainComponentMapper info={info}/>
		) : ( // Input Component
      <ToolchainComponentMapper info={info}/>
		)}
		</>
	)
}